config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  # get 'books/edit'
  # resources :books
  devise_for :users
  # get 'homes/top'd
  # get 'top' => 'homes#top'
  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  resources :books, only: [:index, :show, :new,:edit, :create,:update, :destroy]
  resources :users, only: [:show, :edit, :index, :update, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

 belongs_to :user
has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord

  # before_action :is_matching_login_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { minimum: 2, maximum: 20 }

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  # def after_sign_out_path_for(resource)
  #   about_path
  # end


  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :is_matching_login_user ,only: [:updete, :edit]
  def new
    @book = Book.new
    @books = Book.all
    @user = @books
  end

   # 投稿データの保存
  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice]= "Book was successfully created."
      redirect_to book_path(@book_new.id)
    else
     @user =@book_new.user
     @books = Book.all
     render template: "users/show"

    end
  end


  def index
    @book_new = Book.new
    @books = Book.all
    @user = current_user

  end


  def show
     @book_new  = Book.new
     @book = Book.find(params[:id])
     @user = @book.user
  end

  def edit
     @book = Book.find(params[:id])
    # @user = current_user
     @book_new=Book.new

  end

  def update
     @book = Book.find(params[:id])
   if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
   else
        # 保存に失敗したとき
      @books = Book.all
      render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    @book.destroy
    redirect_to books_path
  end

  # def correct_user
  #   @book = Book.find(params[:id])
  #   redirect_to(books_path) unless current_user?(@book.user)
  # end

  # def current_user?(user)
  #     user == current_user
  # end

  private

  def book_params
    params.require(:book).permit(:title, :body,:profile_image)

  end

  def is_matching_login_user
     user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path 
    end
  end





end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end
def about
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :correct_user, only: [:update]
  before_action :is_matching_login_user ,only: [:updete, :edit]
  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book_new = Book.new


  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @user = current_user
    @users = User.all
    @book_new = Book.new



  end
  def create
    @user = User.new(user_params)
    @uer.user_id = current_user.id
    @user.save
    redirect_to users_path(@user.id)
  end




  def update
   @user = User.find(params[:id])

    if  @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      @user.save
     redirect_to user_path(@user.id)
    else
      @users=User.all
      render :edit

    end

  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
        <br>
        <br>
        <h2>New book</h2>

        <%= form_with model: book, url: '/books', method: :post do |f| %>
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
            <p>Opinion</p>
            <%= f.text_area :body %>

               <i class="fa-solid fa-book-open-reader"></i>
              <%= f.submit 'Create Book' %>

        <% end %>

app/views/books/edit.html.erb
  <p id="notice"></p>  <%= flash[:notice] %>
  <div class='container'>
  <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>Editing Book</h2>
  <% if @book.errors.any? %>
   <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
     <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
  </ul>
  <% end %>
 <%= form_with model: @book do |f| %>
  <h4>Title</h4>
   <%= f.text_field :title %>
   <h4>Opinion</h4>
    <%= f.text_area :body%>
   <p>ユーザーネーム：<%= @book.user.name %></p>
  </br>
  <%= f.submit 'Update Book' %>
  <br>
   <td><%= link_to "Show", book_path(@book.id) %></td>
   |
  <td><%= link_to "Back", books_path %></td>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'users/user', user: @user %>
<%= render 'books/book', book: @book_new %>
</div>
<div class ="col-md-8 offset-md-1">
<br>
<br>
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead><th></th>
<th>Title</th>
<th>Opinion</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>

<% @books.each do |book| %>
<tr>
  <td><%=link_to user_path(book.user) do %>
  <%= image_tag book.user.get_profile_image(80,80) %><% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td></td>
  <td><%= book.body%></td>
 </tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<div>
        <h2>New book</h2>

        <%= form_with model: @book, url: '/books', method: :post do |f| %>
            <p>Title</p><%= f.text_field :title %>
            <p>Opinion</p><%= f.text_area :body %>

            <br><%= f.submit 'Create Book' %>
        <% end %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
<div class="row">
<div class="col-md-3">
<%= render 'users/user', user: @user %>
<%= render 'books/book', book: @book_new %>
</div>

<div class ="col-md-8 offset-md-1">
<br>
<br>
<h1>Book detail</h1>
<table class="table table-hover table-inverse">
<thead><tr><th></th>
<th></th>
<th></th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<tr>
  <td><%= link_to image_tag(@user.get_profile_image(80,80)),user_path(@user.id) %>
  <p><%=link_to @user.name,user_path(@user.id) %></p>
  </td>
  <td><%= link_to @book.title, book_path(@book.id) %></td></td>
  <td><%= @book.body %></td>
  <td> <% if @book.user == current_user %>
  <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
  <td><%= link_to "Destroy",book_path(@book.id) ,method: :delete, "data-confirm" => "本当に削除しますか？" %>
    </td>
     </tr>
      <% end %>
      </tbody>
    </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p><%= flash[:notice] %></p></p>
 <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <center><h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>☆</h1>
      <p>In <i class="fas fa-book"></i>Bookers</p>
      <p>A lot of contributions will post a favorite book!</p></center>
      <div class="btn-wrapper col-10 mx-auto">
      <div class="row">

        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>

         </div>
         <div class="row">

            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/756069d44a.js" crossorigin="anonymous"></script>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <a class="navbar-brand"href="/">Bookers</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
          <li>
          <%= link_to user_path(current_user),class:'nav-link text-light' do %>
          <i class="fas fa-home"></i>Home<% end %>
          </i>
         </li>
        <li>
        <%= link_to users_path,class:'nav-link text-light' do %>
      <i class="fas fa-users"></i>Users<% end %>
         </li>
         <li>
         <%= link_to books_path,class:'nav-link text-light' do %>
      <i class="fas fa-book-open"></i>Books<% end %>
          </li>
      <li>
      <%= link_to destroy_user_session_path, method: :delete ,class:'nav-link text-light' do %>
    <i class="fas fa-sign-out-alt"></i>Log out<% end %>
      </li>
     <% else %>
    <li>
    <%= link_to root_path, class:'nav-link text-light' do %>
      <i class="fas fa-home"></i>Home<% end %>
    </li>
    <li>
    <%= link_to home_about_path, class: 'nav-link text-light' do %>
   <i class="fas fa-link"></i>About<% end %>
    </li>

      <li>
       <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
   <i class="fas fa-user-plus"></i>Sign up<% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end %>

      </li>
        </div>
              </div>
              </nav>
              </header>
              </li>
            <% end %>
            </ul>

          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-white text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-5">
          </div>
          <div class="col-md-7">
            <h6 class="text-dark mt-2 mb-3">CopyRight Infratop.inc</h6>
            <ul class="p-0 list-unstyled">
              <li>
              </li>
              <li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
        <br>
        <br>
        <h1>User info</h1>
        <%= image_tag user.get_profile_image(100,100) %><br>
        <table class ="table">
          <tbody>
           <tr>
            <td>name</td>
            <td><%= user.name %></td>
            </tr>
           <tr>
          <td>introduction</td>
         <td><%= user.introduction %></td>
        </tr>
        </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
           <% end %>
            </div>

app/views/users/edit.html.erb
        <p id="notice"></p>
      <div class='container'>
  <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>User  info</h1>
  <% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @user do |f| %>

  <h3>name</h3>
  <h3><%= f.text_field:name %></h3>
  <h3>Image<%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %></h3>
  <h3>introduction</h3>
  <h1><%= f.text_field :introduction %></h1>
  <br>
  <%= f.submit 'Update User' %>
<% end %>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
 <div class="col-md-3">
 <%= render 'users/user', user: @user %>
 <%= render 'books/book', book: @book_new %>
 </div>
 <div class ="col-md-8 offset-md-1">
 <br>
<br>
<h2>Users</h2>
<table class="table table-hover table-inverse">
 <thead><tr>
 <th>image</th>
 <th>name</th>
 <th></th>
 <th colspan="3"></th>
 </tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td>
  <%= image_tag user.get_profile_image(80,80) %>
  </td>
  <td><%= user.name %></td></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
 </tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
  <% if @book_new.errors.any? %>
  <%= @book_new.errors.count %>error prohibited this obj from being saved:
  <ul>
      <% @book_new.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <div class="container">
 <div class="row">
 <div class="col-md-3">
<%= render 'users/user', user: @user %>
<%= render 'books/book', book: @book_new %>
 </div>
 <div class ="col-md-8 offset-md-1">
 <br>
 <h1>Books</h1>
<table class="table table-hover table-inverse">
 <thead><tr><th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
  </tr>
 </thead>
<tbody>

<% @books.each do |book| %>
<tr>
  <td><%=link_to user_path(book.user) do %>
  <%= image_tag book.user.get_profile_image(80,80) %><% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td></td>
  <td><%= book.body%></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>